2024-01-24 01:37:53,956 ERROR 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<aiogram.utils.keyboard.I...t at 0x00000230E49B17E0>, input_type=InlineKeyboardBuilder]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<aiogram.utils.keyboard.I...t at 0x00000230E49B17E0>, input_type=InlineKeyboardBuilder]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<aiogram.utils.keyboard.I...t at 0x00000230E49B17E0>, input_type=InlineKeyboardBuilder]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<aiogram.utils.keyboard.I...t at 0x00000230E49B17E0>, input_type=InlineKeyboardBuilder]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
2024-01-24 01:40:19,021 ERROR ssssssssss
2024-01-24 02:08:58,313 INFO BEGIN (implicit)
2024-01-24 02:08:58,313 INFO ROLLBACK
2024-01-24 02:10:23,239 INFO BEGIN (implicit)
2024-01-24 02:10:23,239 INFO PRAGMA main.table_info("user")
2024-01-24 02:10:23,239 INFO [raw sql] ()
2024-01-24 02:10:23,241 INFO COMMIT
2024-01-24 02:10:44,055 INFO BEGIN (implicit)
2024-01-24 02:10:44,055 INFO PRAGMA main.table_info("user")
2024-01-24 02:10:44,055 INFO [raw sql] ()
2024-01-24 02:10:44,056 INFO PRAGMA temp.table_info("user")
2024-01-24 02:10:44,056 INFO [raw sql] ()
2024-01-24 02:10:44,057 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-01-24 02:10:44,057 INFO [no key 0.00009s] ()
2024-01-24 02:10:44,064 INFO COMMIT
2024-01-24 02:10:53,678 ERROR Cause exception while process update id=478745571 by bot id=6258570193
AttributeError: __enter__
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 16, in cmd_start
    with SessionLocal() as session:
AttributeError: __enter__
2024-01-24 02:12:26,472 INFO BEGIN (implicit)
2024-01-24 02:12:26,472 INFO PRAGMA main.table_info("user")
2024-01-24 02:12:26,472 INFO [raw sql] ()
2024-01-24 02:12:26,473 INFO COMMIT
2024-01-24 02:12:28,612 ERROR Cause exception while process update id=478745572 by bot id=6258570193
AttributeError: 'AsyncSession' object has no attribute 'query'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 17, in cmd_start
    user = session.query(models.User).filter_by(id_user=message.from_user.id).first()
AttributeError: 'AsyncSession' object has no attribute 'query'
2024-01-24 02:13:28,675 INFO BEGIN (implicit)
2024-01-24 02:13:28,675 INFO PRAGMA main.table_info("user")
2024-01-24 02:13:28,675 INFO [raw sql] ()
2024-01-24 02:13:28,676 INFO COMMIT
2024-01-24 02:13:30,283 ERROR Cause exception while process update id=478745573 by bot id=6258570193
AttributeError: 'AsyncSession' object has no attribute 'query'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 17, in cmd_start
    user = await session.query(models.User).filter_by(id_user=message.from_user.id).first()
AttributeError: 'AsyncSession' object has no attribute 'query'
2024-01-24 02:17:23,875 INFO BEGIN (implicit)
2024-01-24 02:17:23,875 INFO PRAGMA main.table_info("user")
2024-01-24 02:17:23,875 INFO [raw sql] ()
2024-01-24 02:17:23,876 INFO COMMIT
2024-01-24 02:17:25,997 ERROR Cause exception while process update id=478745574 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'first'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 19, in cmd_start
    user = await session.execute(select(models.User).filter_by(id_user=message.from_user.id)).first()
AttributeError: 'coroutine' object has no attribute 'first'
2024-01-24 02:19:29,095 INFO BEGIN (implicit)
2024-01-24 02:19:29,095 INFO PRAGMA main.table_info("user")
2024-01-24 02:19:29,095 INFO [raw sql] ()
2024-01-24 02:19:29,097 INFO COMMIT
2024-01-24 02:19:31,382 ERROR Cause exception while process update id=478745575 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'first'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 19, in cmd_start
    user = await session.execute(select(models.User).filter_by(id_user=message.from_user.id)).first()
AttributeError: 'coroutine' object has no attribute 'first'
2024-01-24 02:20:38,425 INFO BEGIN (implicit)
2024-01-24 02:20:38,425 INFO PRAGMA main.table_info("user")
2024-01-24 02:20:38,426 INFO [raw sql] ()
2024-01-24 02:20:38,427 INFO COMMIT
2024-01-24 02:20:41,479 ERROR Cause exception while process update id=478745576 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'scalars'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 19, in cmd_start
    user = await session.execute(select(models.User).filter_by(id_user=message.from_user.id)).scalars().first()
AttributeError: 'coroutine' object has no attribute 'scalars'
2024-01-24 02:21:03,289 INFO BEGIN (implicit)
2024-01-24 02:21:03,289 INFO PRAGMA main.table_info("user")
2024-01-24 02:21:03,289 INFO [raw sql] ()
2024-01-24 02:21:03,290 INFO COMMIT
2024-01-24 02:21:04,632 ERROR Cause exception while process update id=478745577 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'filter_by'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 19, in cmd_start
    user = await session.execute(select(models.User)).filter_by(id_user=message.from_user.id).scalars().first()
AttributeError: 'coroutine' object has no attribute 'filter_by'
2024-01-24 02:21:26,748 INFO BEGIN (implicit)
2024-01-24 02:21:26,750 INFO PRAGMA main.table_info("user")
2024-01-24 02:21:26,750 INFO [raw sql] ()
2024-01-24 02:21:26,751 INFO COMMIT
2024-01-24 02:21:37,914 ERROR Cause exception while process update id=478745578 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'filter_by'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 19, in cmd_start
    user = await session.execute(select(models.User)).filter_by(id_user=message.from_user.id).first()
AttributeError: 'coroutine' object has no attribute 'filter_by'
2024-01-24 02:22:19,236 INFO BEGIN (implicit)
2024-01-24 02:22:19,236 INFO PRAGMA main.table_info("user")
2024-01-24 02:22:19,236 INFO [raw sql] ()
2024-01-24 02:22:19,237 INFO COMMIT
2024-01-24 02:22:20,679 INFO BEGIN (implicit)
2024-01-24 02:22:20,681 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user
2024-01-24 02:22:20,681 INFO [generated in 0.00015s] ()
2024-01-24 02:22:20,682 INFO ROLLBACK
2024-01-24 02:22:20,683 ERROR Cause exception while process update id=478745579 by bot id=6258570193
AttributeError: 'NoneType' object has no attribute 'first'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 20, in cmd_start
    user = result.scalar().first()
AttributeError: 'NoneType' object has no attribute 'first'
2024-01-24 02:23:21,337 INFO BEGIN (implicit)
2024-01-24 02:23:21,338 INFO PRAGMA main.table_info("user")
2024-01-24 02:23:21,338 INFO [raw sql] ()
2024-01-24 02:23:21,339 INFO COMMIT
2024-01-24 02:23:22,723 INFO BEGIN (implicit)
2024-01-24 02:23:22,725 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user
2024-01-24 02:23:22,725 INFO [generated in 0.00016s] ()
2024-01-24 02:23:22,726 INFO ROLLBACK
2024-01-24 02:23:22,727 ERROR Cause exception while process update id=478745580 by bot id=6258570193
AttributeError: 'NoneType' object has no attribute 'first'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 20, in cmd_start
    user = result.scalar().first()
AttributeError: 'NoneType' object has no attribute 'first'
2024-01-24 02:26:35,971 INFO BEGIN (implicit)
2024-01-24 02:26:35,971 INFO PRAGMA main.table_info("user")
2024-01-24 02:26:35,971 INFO [raw sql] ()
2024-01-24 02:26:35,972 INFO COMMIT
2024-01-24 02:26:39,449 ERROR Cause exception while process update id=478745581 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'scalar_one_or_none'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 20, in cmd_start
    user = session.execute(query).scalar_one_or_none()
AttributeError: 'coroutine' object has no attribute 'scalar_one_or_none'
2024-01-24 02:26:54,830 INFO BEGIN (implicit)
2024-01-24 02:26:54,831 INFO PRAGMA main.table_info("user")
2024-01-24 02:26:54,831 INFO [raw sql] ()
2024-01-24 02:26:54,832 INFO COMMIT
2024-01-24 02:26:56,468 ERROR Cause exception while process update id=478745582 by bot id=6258570193
AttributeError: 'coroutine' object has no attribute 'scalar_one_or_none'
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 20, in cmd_start
    user = await session.execute(query).scalar_one_or_none()
AttributeError: 'coroutine' object has no attribute 'scalar_one_or_none'
2024-01-24 02:27:25,220 INFO BEGIN (implicit)
2024-01-24 02:27:25,220 INFO PRAGMA main.table_info("user")
2024-01-24 02:27:25,220 INFO [raw sql] ()
2024-01-24 02:27:25,222 INFO COMMIT
2024-01-24 02:27:26,505 INFO BEGIN (implicit)
2024-01-24 02:27:26,506 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:27:26,507 INFO [generated in 0.00017s] (38676703,)
2024-01-24 02:27:26,508 ERROR None
2024-01-24 02:27:26,508 INFO ROLLBACK
2024-01-24 02:27:26,509 ERROR Cause exception while process update id=478745583 by bot id=6258570193
TypeError: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\andel\Desktop\aiogram3pattern\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\andel\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\andel\Desktop\aiogram3pattern\handlers\start.py", line 27, in cmd_start
    await session.add(user)
TypeError: object NoneType can't be used in 'await' expression
2024-01-24 02:28:08,726 INFO BEGIN (implicit)
2024-01-24 02:28:08,726 INFO PRAGMA main.table_info("user")
2024-01-24 02:28:08,727 INFO [raw sql] ()
2024-01-24 02:28:08,728 INFO COMMIT
2024-01-24 02:28:12,039 INFO BEGIN (implicit)
2024-01-24 02:28:12,041 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:28:12,041 INFO [generated in 0.00016s] (38676703,)
2024-01-24 02:28:12,045 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-01-24 02:28:12,045 INFO [generated in 0.00016s] (38676703, 'MrDeliDev', 'Andrey Deli')
2024-01-24 02:28:12,048 INFO COMMIT
2024-01-24 02:28:23,033 INFO BEGIN (implicit)
2024-01-24 02:28:23,033 INFO PRAGMA main.table_info("user")
2024-01-24 02:28:23,033 INFO [raw sql] ()
2024-01-24 02:28:23,034 INFO COMMIT
2024-01-24 02:29:41,830 INFO BEGIN (implicit)
2024-01-24 02:29:41,830 INFO PRAGMA main.table_info("user")
2024-01-24 02:29:41,830 INFO [raw sql] ()
2024-01-24 02:29:41,832 INFO COMMIT
2024-01-24 02:29:44,198 INFO BEGIN (implicit)
2024-01-24 02:29:44,200 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:29:44,200 INFO [generated in 0.00019s] (38676703,)
2024-01-24 02:29:44,201 INFO COMMIT
2024-01-24 02:30:06,892 INFO BEGIN (implicit)
2024-01-24 02:30:06,892 INFO PRAGMA main.table_info("user")
2024-01-24 02:30:06,892 INFO [raw sql] ()
2024-01-24 02:30:06,894 INFO PRAGMA temp.table_info("user")
2024-01-24 02:30:06,894 INFO [raw sql] ()
2024-01-24 02:30:06,895 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-01-24 02:30:06,895 INFO [no key 0.00010s] ()
2024-01-24 02:30:06,902 INFO COMMIT
2024-01-24 02:30:12,281 INFO BEGIN (implicit)
2024-01-24 02:30:12,283 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:30:12,283 INFO [generated in 0.00017s] (38676703,)
2024-01-24 02:30:12,287 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-01-24 02:30:12,287 INFO [generated in 0.00016s] (38676703, 'MrDeliDev', 'Andrey Deli')
2024-01-24 02:30:12,290 INFO COMMIT
2024-01-24 02:30:40,508 INFO BEGIN (implicit)
2024-01-24 02:30:40,509 INFO PRAGMA main.table_info("user")
2024-01-24 02:30:40,509 INFO [raw sql] ()
2024-01-24 02:30:40,510 INFO PRAGMA temp.table_info("user")
2024-01-24 02:30:40,510 INFO [raw sql] ()
2024-01-24 02:30:40,511 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-01-24 02:30:40,511 INFO [no key 0.00009s] ()
2024-01-24 02:30:40,519 INFO COMMIT
2024-01-24 02:30:42,362 INFO BEGIN (implicit)
2024-01-24 02:30:42,364 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:30:42,364 INFO [generated in 0.00020s] (38676703,)
2024-01-24 02:30:42,367 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-01-24 02:30:42,367 INFO [generated in 0.00015s] (38676703, 'MrDeliDev', 'Andrey Deli')
2024-01-24 02:30:42,369 INFO COMMIT
2024-01-24 02:39:55,494 INFO BEGIN (implicit)
2024-01-24 02:39:55,494 INFO PRAGMA main.table_info("user")
2024-01-24 02:39:55,494 INFO [raw sql] ()
2024-01-24 02:39:55,495 INFO COMMIT
2024-01-24 02:40:34,448 INFO BEGIN (implicit)
2024-01-24 02:40:34,448 INFO PRAGMA main.table_info("user")
2024-01-24 02:40:34,448 INFO [raw sql] ()
2024-01-24 02:40:34,449 INFO PRAGMA temp.table_info("user")
2024-01-24 02:40:34,449 INFO [raw sql] ()
2024-01-24 02:40:34,450 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-01-24 02:40:34,450 INFO [no key 0.00014s] ()
2024-01-24 02:40:34,459 INFO COMMIT
2024-01-24 02:40:37,194 ERROR AsyncSession.scalars() missing 1 required positional argument: 'statement'
2024-01-24 02:40:42,526 ERROR AsyncSession.scalars() missing 1 required positional argument: 'statement'
2024-01-24 02:41:18,620 INFO BEGIN (implicit)
2024-01-24 02:41:18,620 INFO PRAGMA main.table_info("user")
2024-01-24 02:41:18,620 INFO [raw sql] ()
2024-01-24 02:41:18,621 INFO COMMIT
2024-01-24 02:41:20,217 INFO BEGIN (implicit)
2024-01-24 02:41:20,219 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-24 02:41:20,220 INFO [generated in 0.00019s] (38676703,)
2024-01-24 02:41:20,221 INFO COMMIT
2024-01-24 02:41:20,223 INFO BEGIN (implicit)
2024-01-24 02:41:20,224 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-01-24 02:41:20,224 INFO [generated in 0.00014s] (38676703, 'MrDeliDev', 'Andrey Deli')
2024-01-24 02:41:20,227 INFO COMMIT
2024-01-27 23:30:35,954 INFO BEGIN (implicit)
2024-01-27 23:30:35,954 INFO PRAGMA main.table_info("user")
2024-01-27 23:30:35,954 INFO [raw sql] ()
2024-01-27 23:30:35,955 INFO COMMIT
2024-01-27 23:30:40,674 INFO BEGIN (implicit)
2024-01-27 23:30:40,677 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:30:40,677 INFO [generated in 0.00021s] (38676703,)
2024-01-27 23:30:40,680 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-01-27 23:30:40,680 INFO [generated in 0.00021s] (38676703, 'MrDeliDev', 'Andrey Deli')
2024-01-27 23:30:40,685 INFO COMMIT
2024-01-27 23:30:44,337 INFO BEGIN (implicit)
2024-01-27 23:30:44,337 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:30:44,337 INFO [cached since 3.661s ago] (38676703,)
2024-01-27 23:30:44,339 INFO COMMIT
2024-01-27 23:30:46,323 INFO BEGIN (implicit)
2024-01-27 23:30:46,323 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:30:46,323 INFO [cached since 5.647s ago] (38676703,)
2024-01-27 23:30:46,324 INFO COMMIT
2024-01-27 23:30:47,629 INFO BEGIN (implicit)
2024-01-27 23:30:47,629 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:30:47,629 INFO [cached since 6.952s ago] (38676703,)
2024-01-27 23:30:47,630 INFO COMMIT
2024-01-27 23:30:48,986 INFO BEGIN (implicit)
2024-01-27 23:30:48,986 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:30:48,987 INFO [cached since 8.31s ago] (38676703,)
2024-01-27 23:30:48,988 INFO COMMIT
2024-01-27 23:31:41,445 INFO BEGIN (implicit)
2024-01-27 23:31:41,446 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-01-27 23:31:41,446 INFO [cached since 60.77s ago] (38676703,)
2024-01-27 23:31:41,447 INFO COMMIT
2024-04-02 05:17:17,778 INFO BEGIN (implicit)
2024-04-02 05:17:17,778 INFO PRAGMA main.table_info("user")
2024-04-02 05:17:17,779 INFO [raw sql] ()
2024-04-02 05:17:17,783 INFO PRAGMA main.table_info("people")
2024-04-02 05:17:17,783 INFO [raw sql] ()
2024-04-02 05:17:17,784 INFO PRAGMA temp.table_info("people")
2024-04-02 05:17:17,784 INFO [raw sql] ()
2024-04-02 05:17:17,785 INFO 
CREATE TABLE people (
	id INTEGER NOT NULL, 
	telegram_user_id INTEGER NOT NULL, 
	full_name VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (telegram_user_id)
)


2024-04-02 05:17:17,785 INFO [no key 0.00011s] ()
2024-04-02 05:17:17,792 INFO COMMIT
2024-04-02 05:17:22,266 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:23,613 INFO BEGIN (implicit)
2024-04-02 05:17:23,616 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:17:23,617 INFO [generated in 0.00048s] (694834819,)
2024-04-02 05:17:23,619 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-04-02 05:17:23,619 INFO [generated in 0.00018s] (694834819, 'chebupanfica', 'Anfica Chebupel')
2024-04-02 05:17:23,621 INFO COMMIT
2024-04-02 05:17:27,748 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:32,865 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:38,237 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:43,371 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:48,591 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:54,304 ERROR Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-04-02 05:17:59,508 INFO BEGIN (implicit)
2024-04-02 05:17:59,508 INFO PRAGMA main.table_info("user")
2024-04-02 05:17:59,508 INFO [raw sql] ()
2024-04-02 05:17:59,509 INFO PRAGMA main.table_info("people")
2024-04-02 05:17:59,509 INFO [raw sql] ()
2024-04-02 05:17:59,510 INFO COMMIT
2024-04-02 05:18:01,221 INFO BEGIN (implicit)
2024-04-02 05:18:01,224 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:18:01,224 INFO [generated in 0.00027s] (694834819,)
2024-04-02 05:18:01,225 INFO COMMIT
2024-04-02 05:18:16,201 INFO BEGIN (implicit)
2024-04-02 05:18:16,201 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:18:16,201 INFO [cached since 14.98s ago] (694834819,)
2024-04-02 05:18:16,202 INFO COMMIT
2024-04-02 05:26:14,598 INFO BEGIN (implicit)
2024-04-02 05:26:14,598 INFO PRAGMA main.table_info("user")
2024-04-02 05:26:14,598 INFO [raw sql] ()
2024-04-02 05:26:14,599 INFO PRAGMA main.table_info("people")
2024-04-02 05:26:14,599 INFO [raw sql] ()
2024-04-02 05:26:14,600 INFO COMMIT
2024-04-02 05:26:20,070 INFO BEGIN (implicit)
2024-04-02 05:26:20,073 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:26:20,073 INFO [generated in 0.00035s] (694834819,)
2024-04-02 05:26:20,074 INFO COMMIT
2024-04-02 05:26:53,442 INFO BEGIN (implicit)
2024-04-02 05:26:53,443 INFO PRAGMA main.table_info("user")
2024-04-02 05:26:53,443 INFO [raw sql] ()
2024-04-02 05:26:53,443 INFO PRAGMA main.table_info("people")
2024-04-02 05:26:53,444 INFO [raw sql] ()
2024-04-02 05:26:53,444 INFO COMMIT
2024-04-02 05:26:56,734 INFO BEGIN (implicit)
2024-04-02 05:26:56,736 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:26:56,736 INFO [generated in 0.00019s] (694834819,)
2024-04-02 05:26:56,737 INFO COMMIT
2024-04-02 05:26:59,531 ERROR Cause exception while process update id=640812973 by bot id=7149732794
AttributeError: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 12, in process_fullname
    async with state.proxy() as data:
               ^^^^^^^^^^^
AttributeError: 'FSMContext' object has no attribute 'proxy'
2024-04-02 05:27:14,852 INFO BEGIN (implicit)
2024-04-02 05:27:14,852 INFO PRAGMA main.table_info("user")
2024-04-02 05:27:14,852 INFO [raw sql] ()
2024-04-02 05:27:14,853 INFO PRAGMA temp.table_info("user")
2024-04-02 05:27:14,853 INFO [raw sql] ()
2024-04-02 05:27:14,854 INFO PRAGMA main.table_info("people")
2024-04-02 05:27:14,854 INFO [raw sql] ()
2024-04-02 05:27:14,854 INFO PRAGMA temp.table_info("people")
2024-04-02 05:27:14,855 INFO [raw sql] ()
2024-04-02 05:27:14,855 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-04-02 05:27:14,855 INFO [no key 0.00008s] ()
2024-04-02 05:27:14,861 INFO 
CREATE TABLE people (
	id INTEGER NOT NULL, 
	telegram_user_id INTEGER NOT NULL, 
	full_name VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (telegram_user_id)
)


2024-04-02 05:27:14,861 INFO [no key 0.00014s] ()
2024-04-02 05:27:14,866 INFO COMMIT
2024-04-02 05:27:15,799 INFO BEGIN (implicit)
2024-04-02 05:27:15,802 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:27:15,802 INFO [generated in 0.00028s] (694834819,)
2024-04-02 05:27:15,804 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-04-02 05:27:15,805 INFO [generated in 0.00018s] (694834819, 'chebupanfica', 'Anfica Chebupel')
2024-04-02 05:27:15,807 INFO COMMIT
2024-04-02 05:28:08,080 INFO BEGIN (implicit)
2024-04-02 05:28:08,081 INFO PRAGMA main.table_info("user")
2024-04-02 05:28:08,081 INFO [raw sql] ()
2024-04-02 05:28:08,082 INFO PRAGMA main.table_info("people")
2024-04-02 05:28:08,082 INFO [raw sql] ()
2024-04-02 05:28:08,082 INFO COMMIT
2024-04-02 05:28:10,691 ERROR Cause exception while process update id=640812978 by bot id=7149732794
AttributeError: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 12, in process_fullname
    async with state.proxy() as data:
               ^^^^^^^^^^^
AttributeError: 'FSMContext' object has no attribute 'proxy'
2024-04-02 05:38:29,472 INFO BEGIN (implicit)
2024-04-02 05:38:29,472 INFO PRAGMA main.table_info("user")
2024-04-02 05:38:29,472 INFO [raw sql] ()
2024-04-02 05:38:29,473 INFO PRAGMA main.table_info("people")
2024-04-02 05:38:29,473 INFO [raw sql] ()
2024-04-02 05:38:29,474 INFO COMMIT
2024-04-02 05:38:33,791 INFO BEGIN (implicit)
2024-04-02 05:38:33,794 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:38:33,794 INFO [generated in 0.00020s] (694834819,)
2024-04-02 05:38:33,795 INFO COMMIT
2024-04-02 05:38:36,473 ERROR Cause exception while process update id=640812981 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:38:38,957 ERROR Cause exception while process update id=640812982 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:38:41,068 ERROR Cause exception while process update id=640812983 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:38:46,424 ERROR Cause exception while process update id=640812984 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:39:53,055 INFO BEGIN (implicit)
2024-04-02 05:39:53,055 INFO PRAGMA main.table_info("user")
2024-04-02 05:39:53,055 INFO [raw sql] ()
2024-04-02 05:39:53,056 INFO PRAGMA main.table_info("people")
2024-04-02 05:39:53,056 INFO [raw sql] ()
2024-04-02 05:39:53,057 INFO COMMIT
2024-04-02 05:39:54,625 INFO BEGIN (implicit)
2024-04-02 05:39:54,628 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:39:54,628 INFO [generated in 0.00026s] (694834819,)
2024-04-02 05:39:54,629 INFO COMMIT
2024-04-02 05:39:56,915 ERROR Cause exception while process update id=640812987 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:39:58,296 ERROR Cause exception while process update id=640812988 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:42:57,316 INFO BEGIN (implicit)
2024-04-02 05:42:57,316 INFO PRAGMA main.table_info("user")
2024-04-02 05:42:57,316 INFO [raw sql] ()
2024-04-02 05:42:57,317 INFO PRAGMA main.table_info("people")
2024-04-02 05:42:57,317 INFO [raw sql] ()
2024-04-02 05:42:57,318 INFO COMMIT
2024-04-02 05:43:01,057 INFO BEGIN (implicit)
2024-04-02 05:43:01,060 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-02 05:43:01,060 INFO [generated in 0.00027s] (694834819,)
2024-04-02 05:43:01,061 INFO COMMIT
2024-04-02 05:43:05,549 ERROR Cause exception while process update id=640812992 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 39, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-02 05:43:07,958 ERROR Cause exception while process update id=640812993 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 39, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:36:55,934 INFO BEGIN (implicit)
2024-04-03 04:36:55,935 INFO PRAGMA main.table_info("user")
2024-04-03 04:36:55,935 INFO [raw sql] ()
2024-04-03 04:36:55,939 INFO PRAGMA main.table_info("people")
2024-04-03 04:36:55,939 INFO [raw sql] ()
2024-04-03 04:36:55,940 INFO COMMIT
2024-04-03 04:36:57,030 INFO BEGIN (implicit)
2024-04-03 04:36:57,032 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:36:57,033 INFO [generated in 0.00024s] (694834819,)
2024-04-03 04:36:57,034 INFO COMMIT
2024-04-03 04:37:01,092 ERROR Cause exception while process update id=640812996 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:37:17,838 INFO BEGIN (implicit)
2024-04-03 04:37:17,839 INFO PRAGMA main.table_info("user")
2024-04-03 04:37:17,839 INFO [raw sql] ()
2024-04-03 04:37:17,840 INFO PRAGMA main.table_info("people")
2024-04-03 04:37:17,840 INFO [raw sql] ()
2024-04-03 04:37:17,840 INFO COMMIT
2024-04-03 04:37:19,142 INFO BEGIN (implicit)
2024-04-03 04:37:19,145 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:37:19,145 INFO [generated in 0.00023s] (694834819,)
2024-04-03 04:37:19,146 INFO COMMIT
2024-04-03 04:37:22,420 ERROR Cause exception while process update id=640812999 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:37:24,743 ERROR Cause exception while process update id=640813000 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 16, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:37:55,036 INFO BEGIN (implicit)
2024-04-03 04:37:55,036 INFO PRAGMA main.table_info("user")
2024-04-03 04:37:55,036 INFO [raw sql] ()
2024-04-03 04:37:55,037 INFO PRAGMA main.table_info("people")
2024-04-03 04:37:55,037 INFO [raw sql] ()
2024-04-03 04:37:55,038 INFO COMMIT
2024-04-03 04:37:57,542 INFO BEGIN (implicit)
2024-04-03 04:37:57,544 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:37:57,544 INFO [generated in 0.00020s] (694834819,)
2024-04-03 04:37:57,545 INFO COMMIT
2024-04-03 04:38:11,937 INFO BEGIN (implicit)
2024-04-03 04:38:11,937 INFO PRAGMA main.table_info("user")
2024-04-03 04:38:11,937 INFO [raw sql] ()
2024-04-03 04:38:11,938 INFO PRAGMA main.table_info("people")
2024-04-03 04:38:11,938 INFO [raw sql] ()
2024-04-03 04:38:11,939 INFO COMMIT
2024-04-03 04:42:40,207 INFO BEGIN (implicit)
2024-04-03 04:42:40,207 INFO PRAGMA main.table_info("user")
2024-04-03 04:42:40,207 INFO [raw sql] ()
2024-04-03 04:42:40,208 INFO PRAGMA main.table_info("people")
2024-04-03 04:42:40,208 INFO [raw sql] ()
2024-04-03 04:42:40,209 INFO COMMIT
2024-04-03 04:42:45,211 INFO BEGIN (implicit)
2024-04-03 04:42:45,214 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:42:45,214 INFO [generated in 0.00022s] (694834819,)
2024-04-03 04:42:45,215 INFO COMMIT
2024-04-03 04:42:48,476 ERROR Cause exception while process update id=640813006 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 22, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:42:56,750 ERROR Cause exception while process update id=640813007 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 22, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:42:59,193 ERROR Cause exception while process update id=640813008 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 22, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:43:16,218 INFO BEGIN (implicit)
2024-04-03 04:43:16,219 INFO PRAGMA main.table_info("user")
2024-04-03 04:43:16,219 INFO [raw sql] ()
2024-04-03 04:43:16,219 INFO PRAGMA main.table_info("people")
2024-04-03 04:43:16,220 INFO [raw sql] ()
2024-04-03 04:43:16,220 INFO COMMIT
2024-04-03 04:43:19,653 INFO BEGIN (implicit)
2024-04-03 04:43:19,656 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:43:19,656 INFO [generated in 0.00021s] (694834819,)
2024-04-03 04:43:19,657 INFO COMMIT
2024-04-03 04:43:22,087 INFO BEGIN (implicit)
2024-04-03 04:43:22,088 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 04:43:22,088 INFO [cached since 2.432s ago] (694834819,)
2024-04-03 04:43:22,089 INFO COMMIT
2024-04-03 04:43:24,531 ERROR Cause exception while process update id=640813013 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 22, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 04:43:27,183 ERROR Cause exception while process update id=640813014 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 22, in process_fullname
    await Form.address.set()
          ^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 05:02:33,175 INFO BEGIN (implicit)
2024-04-03 05:02:33,175 INFO PRAGMA main.table_info("user")
2024-04-03 05:02:33,175 INFO [raw sql] ()
2024-04-03 05:02:33,176 INFO PRAGMA main.table_info("people")
2024-04-03 05:02:33,176 INFO [raw sql] ()
2024-04-03 05:02:33,177 INFO COMMIT
2024-04-03 05:02:36,185 ERROR 'State' object has no attribute 'set'
2024-04-03 05:03:28,825 INFO BEGIN (implicit)
2024-04-03 05:03:28,825 INFO PRAGMA main.table_info("user")
2024-04-03 05:03:28,826 INFO [raw sql] ()
2024-04-03 05:03:28,826 INFO PRAGMA main.table_info("people")
2024-04-03 05:03:28,826 INFO [raw sql] ()
2024-04-03 05:03:28,827 INFO COMMIT
2024-04-03 05:03:31,224 INFO BEGIN (implicit)
2024-04-03 05:03:31,227 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 05:03:31,227 INFO [generated in 0.00049s] (694834819,)
2024-04-03 05:03:31,228 INFO COMMIT
2024-04-03 05:04:17,735 ERROR Cause exception while process update id=640813022 by bot id=7149732794
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\photo.py", line 16, in process_photo
    photo_id = message.photo[-1].file_id
               ~~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
2024-04-03 05:04:19,752 ERROR Cause exception while process update id=640813023 by bot id=7149732794
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\photo.py", line 16, in process_photo
    photo_id = message.photo[-1].file_id
               ~~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
2024-04-03 05:08:09,337 INFO BEGIN (implicit)
2024-04-03 05:08:09,337 INFO PRAGMA main.table_info("user")
2024-04-03 05:08:09,337 INFO [raw sql] ()
2024-04-03 05:08:09,339 INFO PRAGMA main.table_info("people")
2024-04-03 05:08:09,339 INFO [raw sql] ()
2024-04-03 05:08:09,340 INFO COMMIT
2024-04-03 05:08:14,791 INFO BEGIN (implicit)
2024-04-03 05:08:14,794 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 05:08:14,794 INFO [generated in 0.00020s] (694834819,)
2024-04-03 05:08:14,795 INFO COMMIT
2024-04-03 05:08:18,758 ERROR Cause exception while process update id=640813027 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\photo.py", line 18, in process_address
    await Form.photo.set()
          ^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 16:02:35,372 INFO BEGIN (implicit)
2024-04-03 16:02:35,373 INFO PRAGMA main.table_info("user")
2024-04-03 16:02:35,373 INFO [raw sql] ()
2024-04-03 16:02:35,374 INFO PRAGMA main.table_info("people")
2024-04-03 16:02:35,374 INFO [raw sql] ()
2024-04-03 16:02:35,374 INFO COMMIT
2024-04-03 16:02:41,647 INFO BEGIN (implicit)
2024-04-03 16:02:41,650 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 16:02:41,650 INFO [generated in 0.00031s] (694834819,)
2024-04-03 16:02:41,652 INFO COMMIT
2024-04-03 16:02:50,012 ERROR Cause exception while process update id=640813163 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\photo.py", line 18, in process_address
    await Form.photo.set()
          ^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 16:11:15,402 INFO BEGIN (implicit)
2024-04-03 16:11:15,402 INFO PRAGMA main.table_info("people")
2024-04-03 16:11:15,402 INFO [raw sql] ()
2024-04-03 16:11:15,403 INFO COMMIT
2024-04-03 16:11:23,215 ERROR Cause exception while process update id=640813166 by bot id=7149732794
AttributeError: 'State' object has no attribute 'set'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\photo.py", line 18, in process_address
    await Form.photo.set()
          ^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'set'
2024-04-03 16:12:41,962 INFO BEGIN (implicit)
2024-04-03 16:12:41,962 INFO PRAGMA main.table_info("people")
2024-04-03 16:12:41,962 INFO [raw sql] ()
2024-04-03 16:12:41,963 INFO COMMIT
2024-04-03 16:12:48,948 ERROR module 'models' has no attribute 'User'
2024-04-03 16:12:52,272 ERROR module 'models' has no attribute 'User'
2024-04-03 16:13:00,452 INFO BEGIN (implicit)
2024-04-03 16:13:00,453 INFO PRAGMA main.table_info("people")
2024-04-03 16:13:00,453 INFO [raw sql] ()
2024-04-03 16:13:00,454 INFO COMMIT
2024-04-03 16:13:01,753 ERROR module 'models' has no attribute 'User'
2024-04-03 16:13:03,584 ERROR module 'models' has no attribute 'User'
2024-04-03 16:13:05,953 ERROR module 'models' has no attribute 'User'
2024-04-03 16:13:47,609 INFO BEGIN (implicit)
2024-04-03 16:13:47,609 INFO PRAGMA main.table_info("people")
2024-04-03 16:13:47,610 INFO [raw sql] ()
2024-04-03 16:13:47,610 INFO PRAGMA temp.table_info("people")
2024-04-03 16:13:47,610 INFO [raw sql] ()
2024-04-03 16:13:47,611 INFO 
CREATE TABLE people (
	id INTEGER NOT NULL, 
	telegram_user_id INTEGER NOT NULL, 
	full_name VARCHAR NOT NULL, 
	location VARCHAR, 
	photo_id VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (telegram_user_id)
)


2024-04-03 16:13:47,611 INFO [no key 0.00009s] ()
2024-04-03 16:13:47,620 INFO COMMIT
2024-04-03 16:13:48,717 ERROR module 'models' has no attribute 'User'
2024-04-03 16:43:22,583 INFO BEGIN (implicit)
2024-04-03 16:43:22,583 INFO PRAGMA main.table_info("people")
2024-04-03 16:43:22,583 INFO [raw sql] ()
2024-04-03 16:43:22,584 INFO COMMIT
2024-04-03 16:43:30,169 ERROR module 'models' has no attribute 'User'
2024-04-03 16:44:54,307 INFO BEGIN (implicit)
2024-04-03 16:44:54,308 INFO PRAGMA main.table_info("people")
2024-04-03 16:44:54,308 INFO [raw sql] ()
2024-04-03 16:44:54,309 INFO COMMIT
2024-04-03 16:44:55,493 ERROR module 'models' has no attribute 'User'
2024-04-03 16:45:07,082 INFO BEGIN (implicit)
2024-04-03 16:45:07,083 INFO PRAGMA main.table_info("people")
2024-04-03 16:45:07,083 INFO [raw sql] ()
2024-04-03 16:45:07,084 INFO COMMIT
2024-04-03 16:45:08,298 ERROR module 'models' has no attribute 'User'
2024-04-03 16:45:34,616 INFO BEGIN (implicit)
2024-04-03 16:45:34,617 INFO PRAGMA main.table_info("people")
2024-04-03 16:45:34,617 INFO [raw sql] ()
2024-04-03 16:45:34,618 INFO COMMIT
2024-04-03 16:45:35,826 ERROR module 'models' has no attribute 'User'
2024-04-03 16:45:37,193 ERROR module 'models' has no attribute 'User'
2024-04-03 16:46:40,698 INFO BEGIN (implicit)
2024-04-03 16:46:40,698 INFO PRAGMA main.table_info("user")
2024-04-03 16:46:40,698 INFO [raw sql] ()
2024-04-03 16:46:40,699 INFO PRAGMA temp.table_info("user")
2024-04-03 16:46:40,699 INFO [raw sql] ()
2024-04-03 16:46:40,700 INFO PRAGMA main.table_info("people")
2024-04-03 16:46:40,700 INFO [raw sql] ()
2024-04-03 16:46:40,701 INFO 
CREATE TABLE user (
	id INTEGER NOT NULL, 
	id_user INTEGER, 
	tg_username VARCHAR, 
	tg_fullname VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (id_user)
)


2024-04-03 16:46:40,701 INFO [no key 0.00010s] ()
2024-04-03 16:46:40,707 INFO COMMIT
2024-04-03 16:46:43,775 INFO BEGIN (implicit)
2024-04-03 16:46:43,784 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 16:46:43,785 INFO [generated in 0.00096s] (694834819,)
2024-04-03 16:46:43,789 INFO INSERT INTO user (id_user, tg_username, tg_fullname) VALUES (?, ?, ?)
2024-04-03 16:46:43,790 INFO [generated in 0.00024s] (694834819, 'chebupanfica', 'Anfica Chebupel')
2024-04-03 16:46:43,792 INFO COMMIT
2024-04-03 16:46:46,773 ERROR Cause exception while process update id=640813182 by bot id=7149732794
AttributeError: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 13, in process_name
    async with state.proxy() as data:
               ^^^^^^^^^^^
AttributeError: 'FSMContext' object has no attribute 'proxy'
2024-04-03 16:46:49,407 ERROR Cause exception while process update id=640813183 by bot id=7149732794
AttributeError: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 13, in process_name
    async with state.proxy() as data:
               ^^^^^^^^^^^
AttributeError: 'FSMContext' object has no attribute 'proxy'
2024-04-03 16:46:51,418 ERROR Cause exception while process update id=640813184 by bot id=7149732794
AttributeError: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 13, in process_name
    async with state.proxy() as data:
               ^^^^^^^^^^^
AttributeError: 'FSMContext' object has no attribute 'proxy'
2024-04-03 17:11:12,539 INFO BEGIN (implicit)
2024-04-03 17:11:12,539 INFO PRAGMA main.table_info("user")
2024-04-03 17:11:12,539 INFO [raw sql] ()
2024-04-03 17:11:12,540 INFO PRAGMA main.table_info("people")
2024-04-03 17:11:12,540 INFO [raw sql] ()
2024-04-03 17:11:12,540 INFO COMMIT
2024-04-03 17:11:16,941 INFO BEGIN (implicit)
2024-04-03 17:11:16,944 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 17:11:16,944 INFO [generated in 0.00019s] (694834819,)
2024-04-03 17:11:16,945 INFO COMMIT
2024-04-03 17:11:23,982 ERROR Cause exception while process update id=640813187 by bot id=7149732794
AttributeError: type object 'Form' has no attribute 'next'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 20, in process_name
    await Form.next()
          ^^^^^^^^^
AttributeError: type object 'Form' has no attribute 'next'
2024-04-03 17:11:29,341 ERROR Cause exception while process update id=640813188 by bot id=7149732794
AttributeError: type object 'Form' has no attribute 'next'
Traceback (most recent call last):
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\middlewares\throttling.py", line 30, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Чебупель.DESKTOP-P8QNSP2\PycharmProjects\My solo bots\Anketa\handlers\address.py", line 20, in process_name
    await Form.next()
          ^^^^^^^^^
AttributeError: type object 'Form' has no attribute 'next'
2024-04-03 17:12:41,878 INFO BEGIN (implicit)
2024-04-03 17:12:41,878 INFO PRAGMA main.table_info("user")
2024-04-03 17:12:41,878 INFO [raw sql] ()
2024-04-03 17:12:41,879 INFO PRAGMA main.table_info("people")
2024-04-03 17:12:41,879 INFO [raw sql] ()
2024-04-03 17:12:41,880 INFO COMMIT
2024-04-03 17:12:47,037 INFO BEGIN (implicit)
2024-04-03 17:12:47,039 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 17:12:47,040 INFO [generated in 0.00020s] (694834819,)
2024-04-03 17:12:47,041 INFO COMMIT
2024-04-03 17:13:58,323 INFO BEGIN (implicit)
2024-04-03 17:13:58,324 INFO PRAGMA main.table_info("user")
2024-04-03 17:13:58,324 INFO [raw sql] ()
2024-04-03 17:13:58,324 INFO PRAGMA main.table_info("people")
2024-04-03 17:13:58,325 INFO [raw sql] ()
2024-04-03 17:13:58,325 INFO COMMIT
2024-04-03 17:14:09,690 INFO BEGIN (implicit)
2024-04-03 17:14:09,693 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 17:14:09,693 INFO [generated in 0.00023s] (694834819,)
2024-04-03 17:14:09,694 INFO COMMIT
2024-04-03 18:15:52,010 INFO BEGIN (implicit)
2024-04-03 18:15:52,011 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 18:15:52,011 INFO [cached since 3702s ago] (694834819,)
2024-04-03 18:15:52,012 INFO COMMIT
2024-04-03 18:16:04,122 INFO BEGIN (implicit)
2024-04-03 18:16:04,122 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 18:16:04,122 INFO [cached since 3714s ago] (694834819,)
2024-04-03 18:16:04,123 INFO COMMIT
2024-04-03 18:35:49,034 INFO BEGIN (implicit)
2024-04-03 18:35:49,034 INFO PRAGMA main.table_info("user")
2024-04-03 18:35:49,034 INFO [raw sql] ()
2024-04-03 18:35:49,035 INFO PRAGMA main.table_info("people")
2024-04-03 18:35:49,035 INFO [raw sql] ()
2024-04-03 18:35:49,036 INFO COMMIT
2024-04-03 18:35:53,710 INFO BEGIN (implicit)
2024-04-03 18:35:53,713 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 18:35:53,713 INFO [generated in 0.00020s] (694834819,)
2024-04-03 18:35:53,714 INFO COMMIT
2024-04-03 19:03:49,480 INFO BEGIN (implicit)
2024-04-03 19:03:49,480 INFO PRAGMA main.table_info("user")
2024-04-03 19:03:49,480 INFO [raw sql] ()
2024-04-03 19:03:49,481 INFO PRAGMA main.table_info("people")
2024-04-03 19:03:49,481 INFO [raw sql] ()
2024-04-03 19:03:49,482 INFO COMMIT
2024-04-03 19:04:01,290 INFO BEGIN (implicit)
2024-04-03 19:04:01,293 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-03 19:04:01,293 INFO [generated in 0.00020s] (694834819,)
2024-04-03 19:04:01,294 INFO COMMIT
2024-04-03 21:05:17,882 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2024-04-03 21:58:19,381 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2024-04-06 05:32:28,085 INFO BEGIN (implicit)
2024-04-06 05:32:28,086 INFO PRAGMA main.table_info("user")
2024-04-06 05:32:28,086 INFO [raw sql] ()
2024-04-06 05:32:28,091 INFO PRAGMA main.table_info("people")
2024-04-06 05:32:28,091 INFO [raw sql] ()
2024-04-06 05:32:28,092 INFO COMMIT
2024-04-06 05:32:39,657 INFO BEGIN (implicit)
2024-04-06 05:32:39,657 INFO PRAGMA main.table_info("user")
2024-04-06 05:32:39,657 INFO [raw sql] ()
2024-04-06 05:32:39,658 INFO PRAGMA main.table_info("people")
2024-04-06 05:32:39,658 INFO [raw sql] ()
2024-04-06 05:32:39,659 INFO COMMIT
2024-04-06 05:32:47,452 INFO BEGIN (implicit)
2024-04-06 05:32:47,455 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-06 05:32:47,455 INFO [generated in 0.00020s] (694834819,)
2024-04-06 05:32:47,456 INFO COMMIT
2024-04-06 05:34:49,145 INFO BEGIN (implicit)
2024-04-06 05:34:49,146 INFO PRAGMA main.table_info("user")
2024-04-06 05:34:49,146 INFO [raw sql] ()
2024-04-06 05:34:49,147 INFO PRAGMA main.table_info("people")
2024-04-06 05:34:49,147 INFO [raw sql] ()
2024-04-06 05:34:49,147 INFO COMMIT
2024-04-06 05:34:55,390 INFO BEGIN (implicit)
2024-04-06 05:34:55,393 INFO SELECT user.id, user.id_user, user.tg_username, user.tg_fullname 
FROM user 
WHERE user.id_user = ?
2024-04-06 05:34:55,393 INFO [generated in 0.00026s] (694834819,)
2024-04-06 05:34:55,394 INFO COMMIT
